import { Rubik } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

// components
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";

const rubik = Rubik({ subsets: ["latin"] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navbar />
      <Sidebar />
      <body className={rubik.className}>
        <div className="main-content">{children}</div>
      </body>
    </html>
  );
}
